### ISSUE TITLE
Update Source while the app is running.

### ISSUE THREAD

**Issue by krris** [macoscope/GrandCentralBoard#26]
Hi! 

You can consider :bulb: changing the source path for `Source`'s while the app is running. As I can see now there is no possibility to change it without restart (for example in `Watch` widget: [link](https://github.com/macoscope/GrandCentralBoard/blob/develop/GrandCentralBoard/Widgets/Watch/Source/EventsSource.swift#L98)).

**Comment by ochococo** [comment]
Internal Jira issue: GCB-230
