### ISSUE TITLE
BonusWidget slows down after tapping Menu button.

### ISSUE THREAD

**Issue by krris** [macoscope/GrandCentralBoard#30]
BonusWidget slows down after tapping Menu button on Apple TV Remote controller.
![screen shot 2016-03-31 at 17 48 04](https://cloud.githubusercontent.com/assets/1786612/14199575/ebf89bd8-f7e5-11e5-9bf2-8c4e4318a74b.png)

**Comment by ochococo** [comment]
Fixed.
