### ISSUE TITLE
Refactor all network calls in widgets to use unified NetworkingBridge.

### ISSUE THREAD

**Issue by ochococo** [macoscope/GrandCentralBoard#94]
On `v1.5` we should have one unified way for HTTP fetches. It can be Bridge over `Alamofire`.

**Comment by ochococo** [comment]
@michallaskowski What do you think?

**Comment by michallaskowski** [comment]
I honestly think we should remove it, and a widget should use any kind of networking it wants to. 
Like, in one widget I am using RxSwift with (Moya)[https://github.com/Moya/Moya], while in the other I see it would greatly benefit from using (Siesta)[github.com/bustoutsolutions/siesta] (Slack for example, where emojis and avatars should be cached).

And there is no benefit in us providing some kind of wrapper, when it is so easy to add a Pod or a framework in a widget.

**Comment by ochococo** [comment]
Agreed. 
So this issue is to be closed but the one that's inside `GCBCore` stays as bridge on Alamofire.
